dependencies:
  - name: mongodb
    version: 3.2
    repository: file://../mongodb
  - name: rabbitmq
    version: 3.0
    repository: file://../rabbitmq
  - name: crawler-bot
    version: 1.0.0
    repository: file://../crawler-bot
  - name: crawler-ui
    version: 1.0.0
    repository: file://../crawler-ui
  - name: nginx-ingress
    version: 1.41.3
    repository: file://../nginx-ingress
